---
version: "3.8"
services:
  movies:
    image: anitalluri00/moviesrepo:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: anitalluri00/trainrepo:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
  dth:
    image: anitalluri00/dthrepo:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  recharge:
    image: anitalluri00/rechargerepo:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
